name: Forked Helper

on:
  push:
  release:
  deployment:
  pull_request:
  workflow_dispatch:

jobs:
  fork-repository-dispatch:
    name: 📢 Run repository dispatch to default fork branch
    if: ${{ github.repository_owner != 'armbian' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Assign secret
      #   id: get_dispatch_secret
      #   run: echo 'name=dispatch_secret::${{ secrets.ARMBIAN_SELF_DISPATCH_TOKEN }}' >> $GITHUB_OUTPUT
      - name: Get event details
        id: get_event_details
        # Process JSON according https://github.com/orgs/community/discussions/26288
        run: |
          JSON=$(cat ${{ github.event_path }})
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "$JSON"
          echo "event_details=${JSON}" >> $GITHUB_OUTPUT

      - name: Debug Event Details
        run: |
          echo ${{ steps.get_event_details.outputs.event_details }}
          echo $(cat ${{ github.event_path }})
          
      - name: Dispatch event on forked repostitory
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ARMBIAN_SELF_DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: armbian
          client-payload: >
            {
              "event": "${{ github.event_name }}",
              "ref": "${{ github.ref }}",
              "base_ref": "${{ github.base_ref }}",
              "sha": "${{ github.sha }}",
              "event_details": ${{ toJson(steps.get_event_details.outputs) }}
            }
