name: Test Armbian dispatch

on:
  repository_dispatch:
    types: ["armbian", "custom"]

jobs:
  show-dispatch:
    name: Show dispatch event details
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
